### ISSUE TITLE
请问authing应该如何配置呢？

### ISSUE THREAD

**Issue by soloveri** [ninthseason/frp-dummy-oidc#1]

**Comment by ninthseason** [comment]
你遇到具体问题我还能试着解决一下，你这样泛泛地问我只好说authing平台那按平台文档配置，frp那按frp文档的oidc示例配置。如果frp连接authing时报错缺少名为xxx参数，就在frp配置里加一条auth.oidc.xxx="你要传递的参数"。

常见的问题是authing平台要求请求时带上scope参数，但frp文档上没提及。所以在frp示例配置的基础上还要加上auth.oidc.scope="你在authing上设定的作用域"

**Comment by soloveri** [comment]
谢谢，我之前遇到的问题是编程用户不存在，查官方文档原来是要建access token，并且使用它的client id，而不是自建应用的client id。
